config/routes.rb
Rails.application.routes.draw do
  root :to => 'students#index'

  resources :students do
    resources :projects
  end
end

app/models/project.rb
require 'textacular'

class Project < ActiveRecord::Base.extend(Textacular)
  belongs_to :student

  validates :title, :presence => true
  validates :description, :presence => true
  validates :url, :presence => true
end

app/models/student.rb
require 'textacular'

class Student < ActiveRecord::Base.extend(Textacular)
  has_many :projects
  validates :name, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.order(params[:sort])
    render :index
  end

  def new
    @student = Student.find(params[:student_id])
    @project = @student.projects.new
  end

  def create
    @student = Student.find(params[:student_id])
    @project = @student.projects.new(project_params)
    if @project.save
      redirect_to student_path(@project.student)
    else
      render
    end
  end

  def show
    @student = Student.find(params[:student_id])
    @project = Project.find(params[:id])
  end

  def edit
    @student = Student.find(params[:student_id])
    @project = Project.find(params[:id])
  end

  def update
    @student = Student.find(params[:student_id])
    @project = Project.find(params[:id])
    if @project.update(project_params)
      redirect_to section_path(@project.student)
    else
      render :edit
    end
  end

  def destroy
  @student = Student.find(params[:student_id])
  @project = Project.find(params[:id])
  @project.destroy
  redirect_to student_path(@project.student)
end

  private
    def project_params
      params.require(:project).permit(:title, :description, :url)
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    @students = Student.order(params[:sort])
    render :index
  end

  def show
    @student = Student.find(params[:id])
    @projects = Project.order(params[:sort])
    render :show
  end

  def edit
    @student = Student.find(params[:id])
    render :edit
  end

  def update
    @student = Student.find(params[:id])
    if @student.update(student_params)
      redirect_to students_path
    else
      render :edit
    end
  end

  # def search(searchTerm)
  #   result = Student.basic_search(searchTerm)


  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      redirect_to students_path
    else
      render :new
    end
  end

  def destroy
    @student = Student.find(params[:id])
    @student.destroy
    redirect_to students_path
  end

  private
  def student_params
    params.require(:student).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_form.html.erb
<%= render "layouts/errors", :object => @student %>

<%= form_for @student do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Epicodus</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container page-wrapper well">
<%= yield %>
</div>
</body>
</html>

app/views/projects/_form.html.erb
<%= render('layouts/errors', :object => @project) %>

<%= form_for [@student, @project] do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.label :url %>
  <%= f.text_field :url %>
  <p><%= f.submit %></p>
<% end %>

app/views/projects/edit.html.erb
<h1>Edit project</h1>

<%= render "form" %>

app/views/projects/new.html.erb
<h1>New project for <%= @student.name %></h1>

<%= render 'form' %>

app/views/projects/show.html.erb
<h1><%= @project.title %></h1>
<h4><%= @project.url %></h4>
<h3><%= @project.description %></h3>

app/views/students/_form.html.erb
<%= form_for @student do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/students/edit.html.erb
<h1>Edit student</h1>

<%= render "form" %>

app/views/students/index.html.erb
<h1>Students</h1>

<div class="container">

<ul>
  <% @students.each do |student| %>
    <li><%=link_to  student.name, student_path(student) %> </li>
  <% end %>
</ul>

<%= link_to "Sort by Name", :sort => "name" %> <br>
<%= link_to "Sort by Date Created", :sort => "created_at" %>

<hr>

<%= link_to "Add a student", new_student_path %>
</div>

app/views/students/new.html.erb
<h1>Add a student</h1>

<%= render 'form' %>

app/views/students/show.html.erb
<h1><%= @student.name %></h1>

<% if @student.projects.any? %>
  <h4>Here are the projects for this student:</h4>

  <ul>
    <% @student.projects.each do |project| %>
      <li>
        <%= link_to project.title, student_project_path(@student, project) %> |
        <%= link_to "Alter", edit_student_project_path(@student, project) %> |
        <%= link_to "Destroy", student_project_path(@student, project),
                                 :data => {:confirm => "Are you sure?",
                                                :method => "delete"} %>
      </li>


    <% end %>
  </ul>

  <%= link_to "Sort by Name", student_path(@student, :sort => "title") %>  <hr>
<% else %>
  <p>There are no projects yet!</p>
<% end %>

<p><%= link_to "Add a project", new_student_project_path(@student) %></p>
<p><%= link_to "Edit", edit_student_path(@student) %></p>
<p><%= link_to "Delete", student_path(@student),
                         :data => {:confirm => "You sure?",
                                   :method => "delete"} %></p>

<p>
  <%= link_to "Return to students", students_path %>
</p>